### ISSUE TITLE
Autologin fails with "Automatically login with Nextcloud user email credentials"

### ISSUE THREAD

**Issue by feutl** [pierre-alain-b/rainloop-nextcloud#134] opened 2020-01-27 08:16 UTC
I am referencing to https://github.com/pierre-alain-b/rainloop-nextcloud/issues/112
But in my case the setting is configured globally to _Automatically login with Nextcloud user email credentials_ and the within the additional settings I have configured email and password.

It was working since one of the last updates, can not really remember which one.
I am using Rainloop 6.0.6 and NC 17.0.2

If I enter the same credentials used in the additional settings within the appearing login screen everything is fine.

Thanks for any help, tipps and guidance to troubleshoot this issue.

**Comment by BOFH90** [comment] 2020-01-30 12:56
I just installed the Rainloop-App in 17.0.2 and can confirm the same issue. 
I find a failed login attampt on my mailserver. It looks like the saved password isn´t used to login.

**Comment by pierre-alain-b** [comment] 2020-01-31 07:02
@piti-diablotin, could this be linked with the pull request to improve LDAP compatiblity? https://github.com/pierre-alain-b/rainloop-nextcloud/pull/111 
I do not see the problem myselb but I am tempted to reverse this change to see if this fixes the issue.

**Comment by piti-diablotin** [comment] 2020-01-31 07:17
@pierre-alain-b It is probably the case. I am far from home with a very bad internet connection so I cannot look into it right now
What I can imagine is with the "autologin with user email" the email is taken from LDAP but the password is taken from NC. Let's imagine 2 cases:
1. NC server on mydomain, login user, password pwd and email user@mydomain. password for emaili is the same password pwd -> Should work fine (this is my configuration)
2. NC server on mydomain, login user, password pwd and email user@toto, password for email is pwd2 -> will fail since both password are different. 

I guess @feutl  and @BOFH90 are in case 2.

I don't think the user settings are checked in case autologin is used ? were they before with the legacy autologin ?

**Comment by feutl** [comment] 2020-01-31 07:39
`Automatically login with Nextcloud user email credentials` being used in my case.
My NC server is hosted inhouse, the mail servers are hosted externally. The user just fills out its password and email (which I support @gmail.com, @feutl.com, @outlook.com, etc.) under user > additional settings to have a ad- and tracking free webmailer :)

And yes the passwords for the nextcloud instance and the mail accounts are different, I could sync them manually but it won't make sense, because after a password change on NC by the user we are out of sync.

thanks

**Comment by feutl** [comment] 2020-02-03 10:03
what is the status, this is bugging me a lot and I would like to avoid installing a previous package (if this even works without problems).
Thanks

**Comment by piti-diablotin** [comment] 2020-02-03 10:56
@feutl Actually, this `Automatically login with Nextcloud user email credentials` was designed mainly for mails on the same domain name with the same password for LDAP users. 
The mail and password must be the same as for the legacy `Automatically login with Nextcloud  credentials`.
In the case the mail is not part of the domain name and the password does not match the one from NC then I would not activate the autologin. 
Indeed, activated or not the user will have to enter the password in his/her settings. Then it is no more automatic ...
If no autologin is activated, the user can enter his/her mail+password to autologin. This will produce exactly the result you want I think.
What I will add if @pierre-alain-b is ok with that is an additionnal check: if one of the autologin is checked but the user provide credentiels, then these ones will be use. Would that be ok with you ?

@pierre-alain-b See my commit [86d87c8ac9ac3a21ce574b46ae4739c369b11dfc](https://github.com/piti-diablotin/rainloop-nextcloud/commit/86d87c8ac9ac3a21ce574b46ae4739c369b11dfc)
I'll fix the spacings if needed

**Comment by pierre-alain-b** [comment] 2020-02-03 12:15
I am fine with that. Worth a try!

**Comment by feutl** [comment] 2020-02-03 12:22
hahaha, now I get it :)
You are right, now I understand. I think the naming of the radio buttons is not very clear.
Using
![image](https://user-images.githubusercontent.com/8522012/73652811-0618b300-4688-11ea-8ec2-f45eb78cbb30.png)
with the settings for the rainloop user
![image](https://user-images.githubusercontent.com/8522012/73652830-12047500-4688-11ea-880e-a81b93c7d48c.png)
works as expected.

Perhaps we could just "rename" the label to explain the admin, if they use `Do not automatically login` it pulls the data (if exists) from the additional user settings "RainLoop Webmail"

Thanks

**Comment by BOFH90** [comment] 2020-02-03 12:50
okay, i also find the naming confusing. It does indeed work with your settings :)

**Comment by piti-diablotin** [comment] 2020-02-05 08:46
Please review #136  to see if this would work better than the actual naming. Or propose something ?
Also we would need to update translations.
I can do French but don't know exactly how to proceed.

**Comment by pierre-alain-b** [comment] 2020-02-05 20:32
- I do understand the new wording but I let others comment.
- For the translation, I don't think a French translation exists... but you can just replicate the PL translation that is available in the rainloop/l10n/pl.js and pl.json (I don't know why both files are needed that said), but I haven't tested

**Comment by pierre-alain-b** [comment] 2020-02-05 20:32
I am closing the issue because I think the cause is now treated.

**Closed as completed by pierre-alain-b** 2020-02-05 20:32 UTC
