### ISSUE TITLE
RainLoop data folder is accessible

### ISSUE THREAD

**Issue by kees-closed** [pierre-alain-b/rainloop-nextcloud#63] opened 2018-05-25 15:32 UTC
I only now noticed the following error in the admin page. The documentation it referrers to is to Rainloop itself, not really the situation in Nextcloud as an app. Is there some documentation about this?

![screenshot from 2018-05-25 17-26-05](https://user-images.githubusercontent.com/6113099/40552874-51dc1f72-6041-11e8-8eca-b35133bbb0ef.png)

**Comment by pierre-alain-b** [comment] 2018-05-26 05:59
Duplicate of #62

**Closed as completed by pierre-alain-b** 2018-05-26 05:59 UTC
