### ISSUE TITLE
Private email accounts are shown 

### ISSUE THREAD

**Issue by tomastd** [pierre-alain-b/rainloop-nextcloud#150] opened 2020-04-04 19:18 UTC
Hi, I think this might be a bug (Related with Nextcloud GDPR).

When a nextcloud user tries to write a new email, in the "To:" section, Rainloop proposes the emails of all the users of the nextcloud instance. Even if they have the email privacy scope set as "Private". As it is in the example below.

![rainloopaccesstoallemails](https://user-images.githubusercontent.com/25134714/78459287-398fb200-76b8-11ea-8ac3-23869212ca06.jpg)

I reported it also in Nextcloud forum because I don't know where exactly the bug is.
https://help.nextcloud.com/t/bug-grdp-compliance-issue-private-email-addresses-are-being-shown/76626

Thank you for your work!!!

**Comment by pierre-alain-b** [comment] 2020-04-05 06:16
Duplicate of https://github.com/pierre-alain-b/rainloop-nextcloud/issues/95

**Comment by pierre-alain-b** [comment] 2020-04-05 06:16
This needs to be changed in the config file of Rainloop as stated in #95:
owncloud_suggestions = On
shall be changed into
owncloud_suggestions = Off
in /path/to/folder/nextcloud/data/rainloop-storage/data/default/configs/application.ini

I hope this helps!

**Closed as completed by pierre-alain-b** 2020-04-05 06:16 UTC

**Comment by tomastd** [comment] 2020-04-05 10:09
I will answer in #95
