### ISSUE TITLE
After the update to 7.2.1 the nextcloud contacts do not appear anymore

### ISSUE THREAD

**Issue by JordanDIG** [pierre-alain-b/rainloop-nextcloud#272] opened 2022-04-07 06:35 UTC
Hello,
I just updated the rainloop application to v16 and the problem is that since the update the nextcloud contacts are no longer displayed in the to field when writing a mail.

CC @pierre-alain-b

**Comment by JordanDIG** [comment] 2022-04-07 06:38
I am in nextcloud 23.0.3.2

**Comment by pierre-alain-b** [comment] 2022-04-07 07:04
Can you clarify which contacts you are referring to? I guess you mean the nextcloud users? correct? As mentioned in #95 ?

**Comment by JordanDIG** [comment] 2022-04-07 07:15
Yes I'm talking about that but the problem is as soon as I change this value, by 'owncloud_suggestions' = On, impossible to access the page and the error Exception: syntax error, unexpected token "=", expecting ")" in file '/var/www//apps/rainloop/app/rainloop/v/1.16.0/app/libraries/RainLoop/Config/Application.php' line 458

> Can you clarify which contacts you are referring to? I guess you mean the nextcloud users? correct? As mentioned in #95 ?

**Comment by JordanDIG** [comment] 2022-04-07 07:45
Can you tell me what the values are and in which file I should edit them? Because I don't really understand...

**Comment by JordanDIG** [comment] 2022-04-07 15:43
I edited the value owncloud_suggestions = Off in the configuration files but I still can't see the contacts. @pierre-alain-b

**Comment by jaycedk** [comment] 2022-04-08 02:56
I'm also having this problem.
Before 7.2.1 my nextcloud contacts would show up in the to field.
![billede](https://user-images.githubusercontent.com/17232146/162353954-b0bf8a8a-ff42-4863-bd6d-204b152d3230.png)
Now there is no contacts.

I have now rolled back to 7.1.3
And that version is working.

**Comment by JordanDIG** [comment] 2022-04-08 05:07
The problem is that I made some changes on my server where my nextcloud is so I can't go back :/

**Comment by pierre-alain-b** [comment] 2022-04-08 05:44
Well, as a temporary fix, you can always re-install the previous version https://github.com/pierre-alain-b/rainloop-nextcloud/releases/download/7.1.3/rainloop.tar.gz.

I am looking at the change in behavior - for now I cannot find what we changed in v1.15 to nextcloud suggestions work and that would have been changed in v1.16.

**Comment by pierre-alain-b** [comment] 2022-04-08 05:51
Are you sure this was working in NC23 with the previous version of Rainloop v1.15 ?

**Comment by jaycedk** [comment] 2022-04-08 06:02
Yes its working in NC23.0.3
![billede](https://user-images.githubusercontent.com/17232146/162373924-5904d9cc-af07-445f-a39a-c1b9cf0c1a77.png)
With Rainloop 1.15.0
![billede](https://user-images.githubusercontent.com/17232146/162374008-d9371e0c-1713-4a68-9fea-7595922d0ea5.png)
![billede](https://user-images.githubusercontent.com/17232146/162374283-9240c630-b63d-4602-bc78-c88165cd3afc.png)

**Comment by scubamuc** [comment] 2022-04-08 06:51
Confirming described issue on multiple instances

- **Nextcloud-snap 23.02** updated Rainloop to 7.2.1 confirming described issue.
   - Downgrading Rainloop on Nextcloud-snap is not an option.
- **Hosted Nextcloud 23.03** updated Rainloop to 7.2.1 confirming described issue.
  - Downgrading Rainloop on hosted instance is not an option.

**Comment by scubamuc** [comment] 2022-04-08 07:45
Workaround for **hosted Nextcloud 23.03** updated to Rainloop 7.2.1
- go to Nextcloud apps
   - deactivate Rainloop 7.2.1 App
   - reactivate Rainloop 7.2.1 App
- contacts preview suggestion is displayed correctly

worked for me...

----
Nextcloud-snap 23.02 updated Rainloop to 7.2.1 described issue remains
   - reactivate Rainloop 7.2.1 App, issue remains
   - restart nextcloud snap, issue remains
   - restart server, not tested!

**Comment by pierre-alain-b** [comment] 2022-04-08 07:47
Interesting, thank you @scubamuc - this would mean the issue is not in the code base. @jaycedk @JordanDIG  can you give it a try?

**Comment by jaycedk** [comment] 2022-04-08 07:55
Just tried @pierre-alain-b just tried, but that did not work for me.
Rolling back again.

**Comment by scubamuc** [comment] 2022-04-08 08:00
@jaycedk sorry to hear didn't work for you
@pierre-alain-b may have been a lucky shot in the dark for hosted Nextcloud 23.03?
Nextcloud-snap 23.02 does not budge

**Comment by scubamuc** [comment] 2022-04-08 08:04
@pierre-alain-b here ist my error log on Nextcloud-Snap 23.02
![grafik](https://user-images.githubusercontent.com/54933878/162392675-d00a12f2-500d-40c2-9cff-fa5667861a78.png)

**Comment by JordanDIG** [comment] 2022-04-08 08:07
> Interesting, thank you @scubamuc - this would mean the issue is not in the code base. @jaycedk @JordanDIG can you give it a try?

I have to deactivate and reactivate the application, right?

**Comment by scubamuc** [comment] 2022-04-08 08:09
@JordanDIG yip, thats how I did it

**Comment by JordanDIG** [comment] 2022-04-08 08:12
This does not work for me.

**Comment by scubamuc** [comment] 2022-04-08 08:13
@pierre-alain-b ... obviously a shot in the dark...

**Comment by pierre-alain-b** [comment] 2022-04-08 09:09
Well, I've made a thorough comparison of ALL the changes between the versions. I found one place which could explain the faulty behavior.
See here: https://github.com/pierre-alain-b/rainloop-nextcloud/commit/449cfadaa77f1f1197bc43ec9fd92ad2c6ee0a4d

Any chance one of you may test this change?

There is one line to change in the app/rainloop/v/1.16.0/app/libraries/RainLoop/Utils.php file.

**Comment by scubamuc** [comment] 2022-04-08 09:41
@pierre-alain-b , sorry no chance to test on Nextcloud-Snap, files are containered. on hosted instance my workaround seems to work still.

**Comment by scubamuc** [comment] 2022-04-08 09:53
@pierre-alain-b , done! success:
![grafik](https://user-images.githubusercontent.com/54933878/162411985-2d4084b5-dea9-450f-ae89-ed1e96607fcb.png)

![grafik](https://user-images.githubusercontent.com/54933878/162412286-b66d33f9-34bf-4240-b3da-b40ee87a919b.png)

this works for Nextcloud-Snap 23.02

Dropdown is now visible, thank you for your help

**Comment by pierre-alain-b** [comment] 2022-04-08 09:54
Excellent, thank you for the test! I will ship 7.2.2 with the correction ASAP!

**Comment by JordanDIG** [comment] 2022-04-08 10:02
I must have made a mistake because it does not work in my home...
I will try again after the update

**Comment by JordanDIG** [comment] 2022-04-08 10:13
So I don't know ...

**Comment by JordanDIG** [comment] 2022-04-08 10:19
> @pierre-alain-b , done! success: ![grafik](https://user-images.githubusercontent.com/54933878/162411985-2d4084b5-dea9-450f-ae89-ed1e96607fcb.png)
> 
> ![grafik](https://user-images.githubusercontent.com/54933878/162412286-b66d33f9-34bf-4240-b3da-b40ee87a919b.png)
> 
> this works for Nextcloud-Snap 23.02
> 
> Dropdown is now visible, thank you for your help

I just remade, I don't have a contact icon next to the source email address

**Comment by jaycedk** [comment] 2022-04-08 10:44
Thank you @pierre-alain-b that made it work again :)

**Comment by JordanDIG** [comment] 2022-04-08 10:54
After setting owncloud_suggestions to off it works again thanks for everything @pierre-alain-b

**Comment by pierre-alain-b** [comment] 2022-04-08 11:45
7.2.2 has just been released. Please update and let me know if it works. If it does, we will then close the ticket. Thanks to everyone for testing/reporting and for your patience and support.

**Comment by daniu-de** [comment] 2022-04-08 12:12
works - thanks - didn't even know that feature but it is surely very useful

**Comment by pierre-alain-b** [comment] 2022-04-08 12:27
Closing on the first report that it works. Good to end the week with this off the plate!

**Closed as completed by pierre-alain-b** 2022-04-08 12:27 UTC
