### ISSUE TITLE
NC 20.0.1 and Rainloop 7.0.3 blank Screen 

### ISSUE THREAD

**Issue by franzpro** [pierre-alain-b/rainloop-nextcloud#215] opened 2020-10-29 17:51 UTC
Hi,

i saw the issue [201 ](https://github.com/pierre-alain-b/rainloop-nextcloud/issues/201).
It sounds like it is already solved after NC19 and Rainloop 7.0.1, but i have the exactly same error pattern (blank screen, only the Top Menue is visible) with NC 20.0.1 and Rainloop 7.0.3
http://xxxxxx:8282/apps/rainloop/

Additionally the admin Page is blank with this URL:
http://xxxxxx:8282/apps/rainloop/app/?admin  
If i change it to: 
http://xxxxxxx:8282/**index.php**/apps/rainloop/app/?admin
the admin page works.

NC is running as jails plugin in a trunas12. Webserver is Nginx
I tried Firefox and Edge

does someone have a tip for me?

thx
Franz

**Comment by gymnae** [comment] 2020-11-02 11:57
Same issue for me, hasn't been working since NC 19.

**Comment by pierre-alain-b** [comment] 2020-11-02 12:05
I have not been able to replicate this issue under NC20 since the patch. Anything else you could report to try to understand the problem here?

**Comment by gymnae** [comment] 2020-11-03 10:25
I try to gather some input:
 ```
'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/webapps/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/media/owncloud/apps',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
```

Rainloop installs in `apps2`

The error message the dev console creates:
`Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://sub.domain.tld/apps/rainloop/app/rainloop/v/1.14.0/static/css/app.min.css?community".`

I see the following red texts in the network tab
Name | Status | Type | Initiator | Size
`rainloop/ | (canceled) | document | /core/js/dist/main.js?v=c8712013-27:1 | Size` 
`?OwnCloudAuth | 500 | document | (index) | 3.4 kB | 112 ms `

I tried adjusting access rights but it didn't change the problem. Only rainloop seems to have problems.

**Comment by pierre-alain-b** [comment] 2020-11-03 12:30
@franzpro is the app also installed in a custom folder in your setting?

**Comment by pierre-alain-b** [comment] 2020-11-03 12:31
This really seems like a "derivative" of https://github.com/pierre-alain-b/rainloop-nextcloud/issues/210

**Comment by franzpro** [comment] 2020-11-03 16:44
Hi, for me the rainloop app folder is located in:
/usr/local/www/nextcloud/apps/

the config.php looks like:

> $CONFIG = array (
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/local/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 =>
    array (
      'path' => '/usr/local/www/nextcloud/apps-pkg',
      'url' => '/apps-pkg',
      'writable' => true,
    ),

**Comment by franzpro** [comment] 2020-11-03 16:52
Hi, is this screenshot helpful?

![Screenshot 2020-11-03 175032](https://user-images.githubusercontent.com/33352129/98015491-2505ca80-1dfd-11eb-9f92-26dd49a1b66b.jpg)

**Comment by ryba84** [comment] 2020-12-01 08:12
Hello. I've this same problem.
When try to access admin interface I'm receiving HTTP error 500, or empty page. It depends which web browser is used.

In attachment NGINX error.log:
[error.log](https://github.com/pierre-alain-b/rainloop-nextcloud/files/5621062/error.log)
and configuration:
[nginx.txt](https://github.com/pierre-alain-b/rainloop-nextcloud/files/5621105/nginx.txt)

**Comment by pierre-alain-b** [comment] 2020-12-01 19:22
thanks @ryba84, the nginx log is useful, we see where the error is:

`Stack trace:
#0 /var/www/html/nc/apps/rainloop/app/rainloop/v/1.14.0/include.php(57): __get_custom_data_full_path()
#1 /var/www/html/nc/apps/rainloop/app/index.php(23): include('/var/www/html/n...')
#2 {main}
  thrown in /var/www/html/nc/apps/rainloop/app/index.php on line 8"`

**Comment by pierre-alain-b** [comment] 2020-12-01 19:30
and
`2020/12/01 08:47:56 [error] 125#125: *32 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /var/www/html/nc/apps/rainloop/app/index.php:8`

has the OC class disappeared in NC 20?

**Comment by ryba84** [comment] 2020-12-09 08:58
Ok. I've managed to overcome this issue. The problem is in nginx configuration. If I use configuration from [latest documentation](https://docs.nextcloud.com/server/20/admin_manual/installation/nginx.html) Rainloop app gives errors like above. But when I use configuration from [Nextcloud 19 documentation](https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html) it's working as expected. I've no time to more tests, but it needs deeper investigate. Seems the nginx configuration from latest (v20) documentation creates problems not only with Rainloop app [#23387](https://github.com/nextcloud/server/issues/23387).
My nginx version is: 1.14.2 from official Debian 10 repositories.

**Comment by daddydaycare** [comment] 2020-12-20 22:43
I only have been using Nextcloud since 19. Rainloop has always been a blank white screen going to admin or the app.  I show it installing in the proper folder. None of the solutions I have read work.  I am using caddyv2 as webserver.

**Comment by gymnae** [comment] 2020-12-23 16:17
I also switched to caddy2, but also switched to the official nextcloud docker image. Since then I have no more issues. rainloop now resides in custom_apps

**Comment by daddydaycare** [comment] 2020-12-29 00:28
> I also switched to caddy2, but also switched to the official nextcloud docker image. Since then I have no more issues. rainloop now resides in custom_apps

I am hosting on truenas in a freebsd jail.

**Comment by dupgit** [comment] 2021-01-15 21:46
I Found how to correct this bug in nginx file configuration from [latest documentation:](https://docs.nextcloud.com/server/20/admin_manual/installation/nginx.html): 
Change line `index index.php index.html /index.php$request_uri;` into `index /index.php /index.html /index.php$request_uri;` and then restart nginx.

**Comment by jolly-jump** [comment] 2021-01-16 13:56
I used the fix: 
https://github.com/nextcloud/documentation/pull/2197#issuecomment-721432337
while they say, that the fix of my previous poster might give delays: https://github.com/nextcloud/documentation/pull/2197#discussion_r530570586

Anyway, I'll cross-reference the LDAP-Problem which originates in the same changes (and somehow wrong documentation): https://github.com/nextcloud/server/issues/16194

**Comment by pierre-alain-b** [comment] 2021-01-18 06:06
OK, thank you for posting solutions, I am therefore closing the issue.

**Closed as completed by pierre-alain-b** 2021-01-18 06:06 UTC

**Comment by nokoa77** [comment] 2021-07-03 08:11
Hi, thank you @jolly-jump your solution rocks !! I had the same issue on NC21, just after switching to official nginx config for NC21
