### ISSUE TITLE
RainLoop data folder is accessible

### ISSUE THREAD

**Issue by feutl** [pierre-alain-b/rainloop-nextcloud#69] opened 2018-07-05 06:11 UTC
I am trying since some days to get rid of this error.
I have the latest Nextcloud 13 installed and pulled Rainloop from the "app store". Everything works quite well, except this error message annoys me.

![image](https://user-images.githubusercontent.com/8522012/42305261-73023cdc-802a-11e8-9a71-80308a271d85.png)

I joined a discussion on help.nextcloud.com
https://help.nextcloud.com/t/warning-rainloop-data-folder-is-accessible/33033/4
to figure it out on my own, but without luck so far.

The problem seems, that the .htaccess files were not created.
The rights and owners of the Nextcloud data directory are correct, the only difference to most others I read about is, that I mounted my data directory outside www and it is a NFS share.

What do I need to do, fixing this issue. Where does the .htaccess needs to go, what must be the content.
How can I help you fixing the issue by investigating the root cause, if possible.

> Is there a log of things going wrong?
> Do I need to place the .htaccess now into
> /media/nextcloud-data/rainloop-storage/_data_
> or
> /media/nextcloud-data/rainloop-storage/
> or/and
> /var/www/html/nextcloud/apps
> or
> /var/www/html/nextcloud/apps/rainloop/app
> This is all not really documented, nor do I understand completely how and what is parsed when.

**Comment by pierre-alain-b** [comment] 2018-07-05 06:16
Hi there,
It's a duplicate of #62. I close this one to move the discussion in #62.

**Closed as completed by pierre-alain-b** 2018-07-05 06:16 UTC
