### ISSUE TITLE
NC disabled Rainloop automaticly

### ISSUE THREAD

**Issue by gruessung** [pierre-alain-b/rainloop-nextcloud#119] opened 2019-11-12 13:26 UTC
My NC disabled Rainloop automaticly without any message. Somtime this happend 1-2 time per week, sometimes 3-4 times per day.
There is no message in NC log.
I have no idea what happend.

**Comment by pierre-alain-b** [comment] 2019-11-18 15:09
I have never seen this.
Have you already tried to uninstall and reinstall rainloop?

**Comment by gnilebein** [comment] 2020-01-18 23:16
I have a similar Problem. In my case it happens when i restart my redis docker container and the redis cache will be cleared.

**Comment by julio1501** [comment] 2020-04-03 12:19
I have a similar Problem.
NC: 16.0.3
Rainloop: 6.0.2
It deactivated itself under high load. 
I have no idea.

**Comment by pierre-alain-b** [comment] 2020-05-15 02:00
Does this happen only to Rainloop or also to other apps?

**Comment by gnilebein** [comment] 2020-05-15 05:29
In my case only rainloop.

**Comment by julio1501** [comment] 2020-05-15 05:43
so far only rainloop.

**Comment by pierre-alain-b** [comment] 2020-05-15 09:11
And this continues to happen regularly? Could you tell me if this still happens with 6.1.2 ? That said, we expect to roll out a new version based on the new app framework (thanks to the excellent work of @nkinkade) so this may bring a solution for this problem without a root cause!

**Comment by gnilebein** [comment] 2020-05-15 10:09
With 6.1.2 nextcloud ist still available after redis restart, but not after server reboot. I have to active it manually again. I have to other problems:

The URL looks strange: https://nextcloud.gnilebein.de/index.php/apps/rainloop/apps/rainloop/ (apps/rainloop twice).

And if you use 'defaultapp' => 'rainloop', in your nextcloud config you get "Too many redirects" while accessing nextcloud.

**Comment by nkinkade** [comment] 2020-05-15 19:48
@pierre-alain-b: I believe what @gnilebein is reporting is caused by #154. It somewhat confirms my suspicion that that was not correct.

**Comment by pierre-alain-b** [comment] 2020-05-17 07:36
The path was reverted in 6.1.4. For NC18, the path is now the old one that worked well.
And for NC19, we need to use your work.
But this does not explain why Rainloop is inactivated "automatically" sometimes in some instances...

**Comment by nkinkade** [comment] 2020-05-20 02:42
Notwithstanding the creator of this issue, the other reports of this happening indicate some other suspicious thing that might be related:

> restart my redis docker container

> under high load

About the only useful thing I could find when searching for this issue was someone saying:

> [Usually apps are disabled if something went wrong or incompatible](https://github.com/nextcloud/server/issues/19232#issuecomment-580683781).

Without logs from Nextcloud, or something relevant from the machine's logs, this issue seems like it will be very, very difficult to uncover, if even possible. Intermittent problems are the worst. :/

My impression from the little information available is that this may not be 100% the RainLoop app's fault, though it does seem likely that the app is brittle in some way. I have no idea whether the App Framework changes pending for v7.x will help this, but it certainly can't hurt.

**Comment by pierre-alain-b** [comment] 2020-05-20 05:21
I agree with this.
7.0.0-beta-3 is out for testing.
if we do not see major regressions in the next couple of days, we will publish 7.0.0 for NC19 (just in time for NC19 out of beta I guess!)

**Comment by pierre-alain-b** [comment] 2020-08-13 13:07
Well without more information, I guess we can say this issue is closed. I am closing now but happy to re-open if this happens again!

**Closed as completed by pierre-alain-b** 2020-08-13 13:07 UTC
Labels: bug, instance-specific, to-be-confirmed
