### ISSUE TITLE
Email Attacments preview does not work in any browser 

### ISSUE THREAD

**Issue by MohammadYaaser** [pierre-alain-b/rainloop-nextcloud#57] opened 2018-03-29 12:32 UTC
I would like to preview Email  attachments , when on clicking the button the attached file should show up as a preview .
 please any help would be appreciated Thanks! #28

**Comment by GoetheG** [comment] 2018-04-24 17:48
Hi @MohammadYaaser,

Unfortunately the whole app seems instable and also insecure. I am thankful for this app being created. But having the General Data Protection Regulation in mind we should be very careful when using this app.

Cheers

**Comment by pierre-alain-b** [comment] 2018-07-06 16:39
Duplicate of #28

**Closed as completed by pierre-alain-b** 2018-07-06 16:39 UTC
