### ISSUE TITLE
Contacts carddav vs NC integrated (*new issue)

### ISSUE THREAD

**Issue by jelle-e** [pierre-alain-b/rainloop-nextcloud#116] opened 2019-11-05 09:39 UTC
Hi,

I've read the issues here about integration and Carddav options.
I have another (privacy) issue here;
Syncing Carddav with the NC URL works fine. I have my address book available in Rainloop.

But, when typing a name in "To:", I get the suggestions of all the users in my NC.
Important to add is that I have everything installed on a Nethserver install which uses an LDAP backend for all users.
So, when adding a user to Nethserver, the user also appears in Nextcloud AND every user is shared with other users in Rainloop through auto-suggest in the TO: field (not though address book / contacts / carddav !)

My question is; why and how is this possible in Rainloop? I would like to block this sharing because of privacy issues, but can I do this in Rainloop or should I look elsewhere? Thanks!

**Comment by pierre-alain-b** [comment] 2019-11-06 06:49
Hi,

Have you tried the solution proposed here?
https://github.com/pierre-alain-b/rainloop-nextcloud/issues/95

I am not sure but it seems to be the same issue.

Let me know.
PAB

**Comment by jelle-e** [comment] 2019-11-06 19:09
Yes! That seems to be the same problem indeed. Only thing is that I can't find

> owncloud_suggestions = On

 anywhere in the rainloop config. When setting: (in Application.php)

> 'owncloud_suggestions' => array(false),

that doesn't seem to change anything.

EDIT:
So, I can't find application.ini anywhere on my system. It's running the Rainloop app that's installed from the webGUI of Nextcloud.

**Comment by pierre-alain-b** [comment] 2019-11-06 21:31
The application.ini is (normally):
'/path/to/nextcloud/data/folder/rainloop-storage/_data_/_default_/configs/application.ini'

**Comment by pierre-alain-b** [comment] 2019-11-09 07:03
Hi Jell-e, did you find the config file?

**Comment by jelle-e** [comment] 2019-11-09 09:21
> Hi Jell-e, did you find the config file?

Even with a "grep -R owncloud_suggestions ./*" from the NC main folder it doesn't find the config, only Application.php. As said; changing the array value to false, doesnt change the behaviour of rainloop.

I don't even have a rainloop-storage folder anywhere.

**Comment by pierre-alain-b** [comment] 2019-11-09 10:33
The application.ini is stored in the data folder, is your data folder stored inside the NC folder? The absence of a rainloop-storage folder would mean that the rainloop is not properly installed.
The "owncloud_suggestions = On" option is an option that says whether all Nextcloud users shall be proposed within Rainloop so for me it is the option to change.

This seems to be an instance specific issue with the lacking rainloop-storage folder so I am closing the issue but I am confident you will have the intended behavior if you reinstall and find the application.ini in the data folder of Nextcloud.

**Closed as completed by pierre-alain-b** 2019-11-09 10:33 UTC

**Comment by jelle-e** [comment] 2019-11-09 11:27
Ah right!! I completely forgot I installed all data on another partition. I found it and now it works. Thanks for you patience ;)

**Comment by pierre-alain-b** [comment] 2019-11-09 11:31
Glad to read that!
